src/main/java/org/folio/rest/delegate/poc/AbstractLoggingDelegate.java
src/main/java/org/folio/rest/delegate/poc/AbstractOkapiRequestDelegate.java
src/main/java/org/folio/rest/delegate/poc/AbstractOkapiRequestRuntimeDelegate.java
src/main/java/org/folio/rest/delegate/poc/AbstractRuntimeDelegate.java
src/main/java/org/folio/rest/delegate/poc/CrCheckInItemDelegate.java
src/main/java/org/folio/rest/delegate/poc/CrExternalCheckInDelegate.java
src/main/java/org/folio/rest/delegate/poc/CrIncrementCheckCountDelegate.java
src/main/java/org/folio/rest/delegate/poc/CrLostItemOkapiRequestDelegate.java
src/main/java/org/folio/rest/delegate/poc/CrPatronNotificationDelegate.java
src/main/java/org/folio/rest/delegate/poc/CrTimerNotifyDelegate.java
src/main/java/org/folio/rest/delegate/poc/CrUpdateLoanStatusDelegate.java
src/main/java/org/folio/rest/delegate/poc/FolioLoginDelegate.java
src/main/java/org/folio/rest/delegate/poc/FolioRefreshTokenDelegate.java
src/main/java/org/folio/rest/delegate/poc/GenericOkapiRequestDelegate.java
src/main/java/org/folio/rest/delegate/poc/MasterSendImeDelegate.java
src/main/java/org/folio/rest/delegate/poc/MasterSendStartMessageDelegate.java
src/main/java/org/folio/rest/delegate/poc/MasterSendTaskDelegate.java
src/main/java/org/folio/rest/delegate/poc/OkapiRequestDelegate.java
src/main/java/org/folio/rest/delegate/poc/ParseOkapiResponseDelegate.java
src/main/java/org/folio/rest/delegate/poc/PrNewOrderNotificationDelegate.java
src/main/java/org/folio/rest/delegate/poc/PrSendRequestNotificationDelegate.java
src/main/java/org/folio/rest/delegate/poc/ResetLoginTokenDelegate.java
src/main/java/org/folio/rest/delegate/poc/System1Delegate.java
src/main/java/org/folio/rest/delegate/poc/TestAccumulatorDelegate.java
src/main/java/org/folio/rest/delegate/poc/TestCreateForEachDelegate.java
src/main/java/org/folio/rest/delegate/poc/TestProcessDelegate.java
src/main/java/org/folio/rest/delegate/poc/TestStreamDelegate.java
src/main/java/org/folio/rest/delegate/poc/ThrowRuntimeErrorDelegate.java

Addresses #4. Move all existing delegates to a POC package for temporary
holding area. Some of these will be promoted down the road as we
determine which are applicable.

Declutter delegates & move to POC package

---

src/main/java/org/folio/rest/delegate/poc/TestAccumulatorDelegate.java
src/main/java/org/folio/rest/delegate/poc/TestCreateForEachDelegate.java
src/main/java/org/folio/rest/delegate/poc/TestProcessDelegate.java
src/main/java/org/folio/rest/delegate/poc/TestStreamDelegate.java

Replace System.out.println() calls with custom logger

---

ramls/accumulatortask.json
ramls/createforeachtask.json
ramls/extractortask.json
ramls/processortask.json
ramls/trigger.json
ramls/workflow.json
src/main/java/org/folio/rest/delegate/poc/TestAccumulatorDelegate.java
src/main/java/org/folio/rest/delegate/poc/TestCreateForEachDelegate.java
src/main/java/org/folio/rest/delegate/poc/TestProcessDelegate.java
src/main/java/org/folio/rest/delegate/poc/TestStreamDelegate.java
src/main/java/org/folio/rest/service/StreamService.java

Sprint1 6 multiple streams

---

ramls/streamcreateforeachtask.json
ramls/workflow.json
src/main/java/org/folio/rest/model/StreamCreateForEachTask.java
src/main/java/org/folio/rest/model/Task.java
src/main/java/org/folio/rest/service/BpmnModelFactory.java

relates TAMULIB/mod-workflow#3

Refactor CreateForEachTask to StreamCreateForEachTask

---

src/main/java/org/folio/rest/delegate/StreamAccumulationDelegate.java

Provide Stream Accumulation Delegate

---

src/main/java/org/folio/rest/delegate/StreamCreateForEachDelegate.java

Provide Stream Create for Each Delegate

---

src/main/java/org/folio/rest/delegate/StreamingProcessDelegate.java

Provide Streaming Process Delegate

---

ramls/extractortask.json
ramls/streamingextractortask.json
ramls/workflow.json
src/main/java/org/folio/rest/delegate/EnhancingExtractorDelegate.java
src/main/java/org/folio/rest/delegate/FolioLoginDelegate.java
src/main/java/org/folio/rest/delegate/StreamAccumulationDelegate.java
src/main/java/org/folio/rest/delegate/StreamCreateForEachDelegate.java
src/main/java/org/folio/rest/model/AccumulatorTask.java
src/main/java/org/folio/rest/model/ExtractorTask.java
src/main/java/org/folio/rest/model/MergeStrategy.java
src/main/java/org/folio/rest/model/ProcessorTask.java
src/main/java/org/folio/rest/service/BpmnModelFactory.java
src/main/java/org/folio/rest/service/StreamService.java
src/main/java/org/folio/rest/utility/ScriptEngineUtility.java
src/main/resources/scripts/engine.js
src/main/resources/scripts/utils.js

This PR contains the work done in sprint 2

Sprint2 staging

---

src/main/resources/scripts/engine.js
src/main/resources/scripts/utils.js

Added UUID class to JS context

---

ramls/scheduletrigger.json
ramls/workflow.json
src/main/java/org/folio/rest/model/ScheduleTrigger.java
src/main/java/org/folio/rest/service/BpmnModelFactory.java

Sprint3 19 scheduled trigger bpmn

---

ramls/restrequesttask.json
ramls/workflow.json
src/main/java/org/folio/rest/delegate/RestRequestDelegate.java
src/main/java/org/folio/rest/model/RestRequestTask.java
src/main/java/org/folio/rest/model/Task.java
src/main/java/org/folio/rest/service/BpmnModelFactory.java

Resp;ves #52 : 
This adds a new delegate RestRequestDelegate and corresponding changes to the BPMN model factory.

Sprint3 52 request task

---

src/main/java/org/folio/rest/delegate/EnhancingExtractorDelegate.java
src/main/java/org/folio/rest/delegate/comparator/PropertyComparator.java
src/main/java/org/folio/rest/service/BpmnModelFactory.java
src/main/java/org/folio/rest/service/StreamService.java

Added a map of comparison pairs

---

ramls/extractortask.json
ramls/streamingextractortask.json
ramls/workflow.json
src/main/java/org/folio/rest/delegate/EnhancingExtractorDelegate.java
src/main/java/org/folio/rest/delegate/OrderedMergingExtractorDelegate.java
src/main/java/org/folio/rest/delegate/comparator/SortingComparator.java
src/main/java/org/folio/rest/delegate/iterable/EnhancingFluxIterable.java
src/main/java/org/folio/rest/service/BpmnModelFactory.java
src/main/java/org/folio/rest/service/StreamService.java
src/test/java/org/folio/rest/service/StreamServiceTest.java

Resolves #69 : 
This changes the BPMNModelFactory to build enhancement service tasks using the new EnhancementComparison and EnhancementMapping lists from mod-workflows's EnhancementTask.
It also utilized modifies the logic in the enhancing flux iteration to work with these lists.

Adds support for enhancementMappings and comparisons

---

ramls/extractortask.json
ramls/streamingextractortask.json
ramls/workflow.json
src/main/java/org/folio/rest/service/BpmnModelFactory.java

[72] Add sortStrategy support to BPMN model factory for ExtractorTask

---

ramls/extractortask.json
ramls/streamingextractortask.json
ramls/workflow.json
src/main/java/org/folio/rest/delegate/StreamingRequestDelegate.java
src/main/java/org/folio/rest/delegate/comparator/PropertyComparator.java
src/main/java/org/folio/rest/delegate/iterable/EnhancingFluxIterable.java
src/main/java/org/folio/rest/service/BpmnModelFactory.java
src/test/java/org/folio/rest/service/StreamServiceTest.java

Sprint5 74 user ref link

---

pom.xml
src/main/java/org/folio/rest/utility/ScriptEngineUtility.java
src/main/resources/scripts/engine.js
src/main/resources/scripts/utils.js

Resolves TAMULib/fm-workflows#7

Sprint6 7 marc to json

---

pom.xml
src/main/java/org/folio/rest/utility/ScriptEngineUtility.java

`JSON.parse(scriptEngineUtility.rawMarcToJson(args.MARC_RECORD))`

Simplify using marc json writer

---

src/main/java/org/folio/rest/delegate/iterable/EnhancingFluxIterable.java

If is multiple create or get array node and add entire input node as an element of the array.
Requires https://github.com/TAMULib/mod-workflow/pull/56

respect enhancement mapping multiple flag

---

ramls/extractortask.json
ramls/streamingextractortask.json
ramls/workflow.json
src/main/java/org/folio/rest/config/WebClientConfig.java
src/main/java/org/folio/rest/delegate/StreamingRequestDelegate.java

Requires spring boot dependency upgrades. https://github.com/folio-org/spring-module-core/pull/22

Webclient http connector

---

ramls/streamingreportingtask.json
ramls/workflow.json
src/main/java/org/folio/rest/controller/WorkflowController.java
src/main/java/org/folio/rest/delegate/AbstractReportableDelegate.java
src/main/java/org/folio/rest/delegate/StreamConsumerDelegate.java
src/main/java/org/folio/rest/delegate/StreamingReportingDelegate.java
src/main/java/org/folio/rest/delegate/StreamingRequestDelegate.java
src/main/java/org/folio/rest/service/BpmnModelFactory.java
src/main/java/org/folio/rest/service/StreamService.java

[89] Add StreamConsumerDelegate

---

ramls/streamingreportingtask.json
ramls/workflow.json
src/main/java/org/folio/rest/delegate/AbstractReportableDelegate.java
src/main/java/org/folio/rest/delegate/StreamingReportingDelegate.java
src/main/java/org/folio/rest/delegate/StreamingRequestDelegate.java
src/main/java/org/folio/rest/service/BpmnModelFactory.java
src/main/java/org/folio/rest/service/StreamService.java

[16] add StreamingReportingDelegate

---

src/main/java/org/folio/rest/utility/ScriptEngineUtility.java

marc field accessors

---

ramls/workflow.json
src/main/java/org/folio/rest/service/BpmnModelFactory.java

Only add login delegate if workflow requires authentication

---

ramls/filereadtask.json
ramls/filewritetask.json
ramls/streamingfilereadtask.json
ramls/streamingfilewritetask.json
ramls/workflow.json
src/main/java/org/folio/rest/delegate/FileExtractorDelegate.java
src/main/java/org/folio/rest/delegate/StreamingFileWriteDelegate.java
src/main/java/org/folio/rest/delegate/StreamingRequestDelegate.java
src/main/java/org/folio/rest/service/BpmnModelFactory.java

Resolves #114 and resolves #115

File Extractor and Writer Delegates

---

src/main/java/org/folio/rest/delegate/DatabaseQueryDelegate.java

Empty string for CSV and TSV. exclude property for JSON.

Issue 132: handle null value from query to csv,tsv,json file

---

pom.xml
ramls/conditionalgateway.json
ramls/databaseconnectiontask.json
ramls/databasedisconnecttask.json
ramls/databasequerytask.json
ramls/directorytask.json
ramls/emailtask.json
ramls/eventsubprocess.json
ramls/filetask.json
ramls/movetonode.json
ramls/parallelgateway.json
ramls/processortask.json
ramls/requesttask.json
ramls/subprocess.json
ramls/workflow.json
src/main/java/org/folio/rest/delegate/Output.java
src/main/java/org/folio/rest/utility/FormatUtility.java
src/main/java/org/folio/rest/utility/MappingUtility.java
src/main/java/org/folio/rest/utility/MarcUtility.java
src/main/java/org/folio/rest/utility/ValidationUtility.java

relates TAMULib/fw-registry/issues/120

Issue 120: Purchase Order Workflow

---

src/main/java/org/folio/rest/delegate/EmailDelegate.java

There are some cases where 4 spaces are used instead of 2.

Consistently use 2-spaces and not 4-spaces for tabbing.

---

src/main/java/org/folio/rest/delegate/AbstractDatabaseOutputDelegate.java
src/main/java/org/folio/rest/delegate/DatabaseQueryDelegate.java

Issue 146: Database query delegate should afford templating the query.

---

src/main/java/org/folio/rest/utility/FormatUtility.java

Add java functions for normalizing CQL and URLs.
related TAMULib/fw-registry/issues/103

fw-registry issue 103: Eresources/Cataloging Workflow: Create brief instance records for new Coral items.

---

src/main/java/org/folio/rest/delegate/DatabaseQueryDelegate.java

This is required for https://github.com/TAMULib/fw-registry/issues/99

Template query output path

---

pom.xml
src/main/java/org/folio/rest/utility/MappingUtility.java

Adds support for parsing CSVs into mapping utils

Csv support

---

src/main/java/org/folio/rest/utility/MappingUtility.java

Describes change in API with mapping rules.

Found hardcoded URL path that changed

---

pom.xml
ramls/emailtask.json
ramls/eventsubprocess.json
ramls/exclusivegateway.json
ramls/inclusivegateway.json
ramls/movetolastgateway.json
ramls/movetonode.json
ramls/parallelgateway.json
ramls/subprocess.json
ramls/workflow.json
src/main/java/org/folio/rest/delegate/EmailDelegate.java

Example use https://github.com/TAMULib/fw-registry/pull/266

Conditionally include attachment

---

ramls/eventsubprocess.json
ramls/exclusivegateway.json
ramls/filetask.json
ramls/inclusivegateway.json
ramls/movetolastgateway.json
ramls/movetonode.json
ramls/parallelgateway.json
ramls/subprocess.json
ramls/workflow.json
src/main/java/org/folio/rest/delegate/FileDelegate.java

Need to only count EOL but Java probably brings in whole line into memory.
Requires https://github.com/folio-org/mod-workflow/pull/58
Blocks https://github.com/TAMULib/fw-registry/issues/272

File task line count and read line

---

pom.xml
src/main/resources/META-INF/bpm-platform.xml

Merged previous staging with current one.
Somehow several commits did not make it into the `main` branch.

Bring in previous sprint's missing commits.

---

src/main/java/org/folio/rest/utility/FormatUtility.java

Follow up to TAMULib/fw-registry#316 .
Only perform simple sanitization.
This function may see future changes if better sanitization is needed.

FW Registry Issue 316: Add simple SQL sanitization.
